services:
  wiki-app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - ${APP_PORT:+"${APP_PORT}:80"}
    restart: always
    environment:
      - APP_ENV=${APP_ENV:-production}
      - SITE_NAME=${SITE_NAME:-Jejeharapan Wiki}
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:80/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
