services:
  wiki-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: corporate-wiki-local
    ports:
      - ${APP_PORT:-8080}:80
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV:-development}
      - SITE_NAME=${SITE_NAME:-Jejeharapan Wiki}
